// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMap.proto

package Ex02;

public interface GameWorldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GameWorld)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MapFloor mapFloor = 1;</code>
   */
  java.util.List<MapFloor>
      getMapFloorList();
  /**
   * <code>repeated .MapFloor mapFloor = 1;</code>
   */
  MapFloor getMapFloor(int index);
  /**
   * <code>repeated .MapFloor mapFloor = 1;</code>
   */
  int getMapFloorCount();
  /**
   * <code>repeated .MapFloor mapFloor = 1;</code>
   */
  java.util.List<? extends MapFloorOrBuilder>
      getMapFloorOrBuilderList();
  /**
   * <code>repeated .MapFloor mapFloor = 1;</code>
   */
  MapFloorOrBuilder getMapFloorOrBuilder(
      int index);
}
