// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMap.proto

package Ex02;

public interface MapFloorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MapFloor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 floorId = 4;</code>
   * @return Whether the floorId field is set.
   */
  boolean hasFloorId();
  /**
   * <code>optional int32 floorId = 4;</code>
   * @return The floorId.
   */
  int getFloorId();

  /**
   * <code>repeated .Tile tile = 5;</code>
   */
  java.util.List<Tile>
      getTileList();
  /**
   * <code>repeated .Tile tile = 5;</code>
   */
  Tile getTile(int index);
  /**
   * <code>repeated .Tile tile = 5;</code>
   */
  int getTileCount();
  /**
   * <code>repeated .Tile tile = 5;</code>
   */
  java.util.List<? extends TileOrBuilder>
      getTileOrBuilderList();
  /**
   * <code>repeated .Tile tile = 5;</code>
   */
  TileOrBuilder getTileOrBuilder(
      int index);
}
