// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMap.proto

package Ex02;

public interface MapFloorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MapFloor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 floorId = 1;</code>
   * @return Whether the floorId field is set.
   */
  boolean hasFloorId();
  /**
   * <code>optional int32 floorId = 1;</code>
   * @return The floorId.
   */
  int getFloorId();

  /**
   * <code>map&lt;string, .Tile&gt; tileMap = 2;</code>
   */
  int getTileMapCount();
  /**
   * <code>map&lt;string, .Tile&gt; tileMap = 2;</code>
   */
  boolean containsTileMap(
      String key);
  /**
   * Use {@link #getTileMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Tile>
  getTileMap();
  /**
   * <code>map&lt;string, .Tile&gt; tileMap = 2;</code>
   */
  java.util.Map<String, Tile>
  getTileMapMap();
  /**
   * <code>map&lt;string, .Tile&gt; tileMap = 2;</code>
   */
  /* nullable */
Tile getTileMapOrDefault(
      String key,
      /* nullable */
Tile defaultValue);
  /**
   * <code>map&lt;string, .Tile&gt; tileMap = 2;</code>
   */
  Tile getTileMapOrThrow(
      String key);
}
