// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameMap.proto

package Ex02;

public interface MapFloorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MapFloor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 floorId = 4;</code>
   * @return Whether the floorId field is set.
   */
  boolean hasFloorId();
  /**
   * <code>optional int32 floorId = 4;</code>
   * @return The floorId.
   */
  int getFloorId();

  /**
   * <code>repeated .Tile tiles = 5;</code>
   */
  java.util.List<Tile>
      getTilesList();
  /**
   * <code>repeated .Tile tiles = 5;</code>
   */
  Tile getTiles(int index);
  /**
   * <code>repeated .Tile tiles = 5;</code>
   */
  int getTilesCount();
  /**
   * <code>repeated .Tile tiles = 5;</code>
   */
  java.util.List<? extends TileOrBuilder>
      getTilesOrBuilderList();
  /**
   * <code>repeated .Tile tiles = 5;</code>
   */
  TileOrBuilder getTilesOrBuilder(
      int index);
}
